### ISSUE TITLE
CSS load issue

### ISSUE THREAD

**Issue by adrienvsj** [technyon/nuki_hub#48] opened 2022-11-18 10:26 UTC
Hello,

Every other time I can't load the CSS of the pages and I get this error in the console : 

`http://192.168.1.26/new.css net::ERR_CONNECTION_RESET`

I have to refresh the page to get the display back.
I use this ESP32: https://www.amazon.fr/gp/product/B08BTLYSTM
I use firmware 6.0

Thank you

**Comment by technyon** [comment] 2022-11-28 19:35
Hi and sorry for the late answer. I don't have an idea really, it works for me. Does the "inter.css" load?

**Comment by technyon** [comment] 2022-11-30 08:56
P.S.: I'm running on wired ethernet. I'll try switching to WiFi and see if I can reproduce the issue.

**Comment by alexdelprete** [comment] 2022-11-30 15:54
I confirm the issue. I'm on wired ethernet with my notebook, but I don't think that how you connect to the network should influence the functionality, you can have more latency, but it should be the same, functionality-wise.

Also, refreshing doesn't help much, it seems random: if I refresh 4-5 times, eventually CSS pulls up, but only one time and in between I see connection reset or the page without CSS.

**Comment by technyon** [comment] 2022-12-01 06:41
I mean I'm on wired ethernet with my ESP, using a W5500 module.

**Comment by alexdelprete** [comment] 2022-12-01 13:44
Oh sorry, I assumed you had a wireless module like me.

**Comment by technyon** [comment] 2022-12-03 07:21
Hi,

I've switched to Wifi for testing, but couldn't reproduce the issue. I'd say it must be something on your end, although it's strange it's always this one file. Can you try with a different browser / computer ?

**Comment by alexdelprete** [comment] 2022-12-03 19:40
I tried with Chrome and Edge. Now I installed Brave on another computer:

![image](https://user-images.githubusercontent.com/7027842/205458850-96d52c8d-4316-42ba-9b2d-3566cd75646c.png)

**Comment by alexdelprete** [comment] 2022-12-03 20:02
I just installed Firefox: it always picks up CSS correctly. So it's something with chrome-based browsers. I don't know if Brave is chrome-based, will check it up. In any case, it should work on all browsers.

![image](https://user-images.githubusercontent.com/7027842/205459623-2a352a7c-3ad8-42e3-9f72-07ad771869b0.png)

**Comment by technyon** [comment] 2022-12-04 08:21
I tried with both Firefox and Chrome and had no issues. Maybe do a clean install of chrome?

**Comment by ruimarinho** [comment] 2023-01-02 12:16
I'm also having the same issue on a fresh install of 6.8.

**Comment by Frank-1964** [comment] 2023-01-24 16:01
Same issue here with nuki_hub 7.2 an Chrome 108.0.5359.71 under Linux Ubuntu.

**Comment by alexdelprete** [comment] 2023-01-24 21:37
Something's not right with the webpage, here's what Edge (chrome based) is reporting:

![image](https://user-images.githubusercontent.com/7027842/214426293-2168238a-bd53-47c9-9bb2-fe3186c7ca9c.png)

The only browser I don't have problems with is Firefox, on ALL chrome-based browsers there's a compatibility issue.

**Comment by technyon** [comment] 2023-01-25 17:02
I'm not a web developer, if someone wants to fix the HTML go ahead :D. The page displays fine except for some users where the CSS for some reason doesn't load. I have no explanation for that, it's static content that's delivered if requested. What's even stranger is that inter.css loads, but new.css doesn't - it's pretty much the same code.

The web page is still usable - it's a simple table based page that is just looks a bit nicer with the CSS.

**Comment by alexdelprete** [comment] 2023-01-25 18:20
> The web page is still usable - it's a simple table based page that is just looks a bit nicer with the CSS.

No it isn't. It takes a lot of time to load, and sometimes it throws errors (RESET, timeout, etc.). I installed Firefox just to use Nuki Hub. :)

I'm not a dev, but I'll check if there are some validation tools online that maybe will optimize the CSS code.

**Comment by technyon** [comment] 2023-01-25 18:52
WebCfgServerConstants.h lines 6 and 10. You'll find the URL where I copied it from in the comments above.

**Comment by alexdelprete** [comment] 2023-01-25 19:25
> P.S.: Still no issue for me, no matter which browser I use.

These things drive me crazy. Many of us have issues with that...on Chrome. How is it possible you have no problems...:)

**Comment by mundschenk-at** [comment] 2023-01-25 20:03
Maybe a different OS/version?

**Comment by alexdelprete** [comment] 2023-01-25 21:58
> Maybe a different OS/version?

We found the problem...and fixed it. Great teamwork on Discord. Join us. :)

**Comment by technyon** [comment] 2023-01-26 16:08
Please check release 7.3

**Comment by regevbr** [comment] 2023-01-26 17:23
> 7.3 works for me now. Thanks :-)

Same here many thanks!

**Comment by technyon** [comment] 2023-01-26 18:01
ok I'll close the issue then

**Closed by technyon** 2023-01-26 18:01 UTC
