### ISSUE TITLE
unable to get battery status

### ISSUE THREAD

**Issue by kujrv1** [technyon/nuki_hub#573] opened 2024-12-24 08:24 UTC
### PROBLEM DESCRIPTION
Unable to get battery status from nuki 4 bluethoot version

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): esp32
- [x] Nuki Hub binary firmware version number used: 9.05
  - [X ] Pre-compiled
  - [ ] Self-compiled
- [ ] Provide the output of http://nukihubIP/info:
```

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by jolichter** [comment] 2024-12-24 09:24
Hi, I can't reproduce the issue. My ESP32-S3 with Nuki Hub 9.05 works without any problems. Check your MQTT DP -> lock.battery.level.

If you encounter any issues, always share your system information.

**Comment by iranl** [comment] 2024-12-24 11:15
Closing for failure to follow the issue template.
You can reopen after providing all required information from the template.

**Closed by iranl** 2024-12-24 11:15 UTC
Labels: template missing/incomplete

**Comment by kujrv1** [comment] 2024-12-24 11:42
factory reset and reconfigured... now.. all data receiving
