### ISSUE TITLE
v9.02 hangs after some days

### ISSUE THREAD

**Issue by leo-b** [technyon/nuki_hub#549] opened 2024-11-30 09:30 UTC
### PROBLEM DESCRIPTION
After upgrading from  to v9.02, my two nuki hubs crash after some days. Unfortunately I don't get any useful log messages, they simply don't respond to http, mqtt or ping requests anymore until a power-cycle.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): ESP32
- [x] Nuki Hub binary firmware version number used: 9.02
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Provide the output of http://nukihubIP/info:

   nuki-hub1:
   
```
System Information

------------ NUKI HUB ------------
Version: 9.02
Build: 11995573722.4.1
Build type: Release
Build date: 2024-11-24
Updater version: 9.02
Updater build: 11995573722.4.1
Updater build date: 2024-11-24
Uptime (min): 907
Config version: 902
Last restart reason FW: NotApplicable
Last restart reason ESP: ESP_RST_POWERON: Reset due to power-on event.
Free internal heap: 68128
Total internal heap: 260580
PSRAM Available: No
Network task stack high watermark: 8628
Nuki task stack high watermark: 5096

------------ GENERAL SETTINGS ------------
Network task stack size: 12288
Nuki task stack size: 8192
Check for updates: No
Latest version: 
Allow update from MQTT: No
Web configurator username: Not set
Web configurator password: Not set
Web configurator enabled: Yes
Publish debug information enabled: No
MQTT log enabled: Yes
Webserial enabled: No
Bootloop protection enabled: No

------------ NETWORK ------------
Network device: Built-in Wi-Fi
Network connected: Yes
IP Address: 10.0.1.91
SSID: ms14-iot
BSSID of AP: B2:B9:8A:60:14:91
ESP32 MAC address: C8:F0:9E:50:1B:D0

------------ NETWORK SETTINGS ------------
Nuki Hub hostname: nuki-eing
DHCP enabled: No
Static IP address: 10.0.1.91
Static IP subnet: 255.255.255.0
Static IP gateway: 10.0.1.1
Static IP DNS server: 10.0.1.1
RSSI Publish interval (s): 10000
Find WiFi AP with strongest signal: Yes
Restart ESP32 on network disconnect enabled: No
MQTT Timeout until restart (s): 600

------------ MQTT ------------
MQTT connected: Yes
MQTT broker address: 10.0.1.1
MQTT broker port: 1883
MQTT username: ***
MQTT password: ***
MQTT base topic: nuki-eing
MQTT SSL CA: Not set
MQTT SSL CRT: Not set
MQTT SSL Key: Not set

------------ BLUETOOTH ------------
Bluetooth TX power (dB): 9
Bluetooth command nr of retries: 3
Bluetooth command retry delay (ms): 100
Seconds until reboot when no BLE beacons received: -1

------------ QUERY / PUBLISH SETTINGS ------------
Lock/Opener state query interval (s): 1800
Publish Nuki device authorization log: Yes
Max authorization log entries to retrieve: 5
Battery state query interval (s): 1800
Most non-JSON MQTT topics disabled: Yes
Publish Nuki device config: Yes
Config query interval (s): 3600
Publish Keypad info: Yes
Keypad query interval (s): 1800
Enable Keypad control: Yes
Publish Keypad topic per entry: No
Publish Keypad codes: No
Allow checking Keypad codes: No
Max keypad entries to retrieve: 10
Publish timecontrol info: No
Keypad query interval (s): 1800
Enable timecontrol control: No
Publish timecontrol topic per entry: No
Max timecontrol entries to retrieve: 10

------------ HOME ASSISTANT ------------
Home Assistant auto discovery enabled: Yes
Home Assistant auto discovery topic: homeassistant/
Nuki Hub configuration URL for HA: http://10.0.1.91

------------ NUKI LOCK ------------
Lock enabled: Yes
Paired: Yes
Nuki Hub device ID: 628801648
Nuki device ID: ***
Firmware version: 3.10.7
Hardware version: 4.10
Valid PIN set: Yes
Has door sensor: No
Has keypad: Yes
Keypad highest entries count: 0
Timecontrol highest entries count: 0
Register as: Bridge

------------ HYBRID MODE ------------
Hybrid mode enabled: No

------------ NUKI LOCK ACL ------------
Lock: Allowed
Unlock: Allowed
Unlatch: Allowed
Lock N Go: Allowed
Lock N Go Unlatch: Allowed
Full Lock: Allowed
Fob Action 1: Allowed
Fob Action 2: Allowed
Fob Action 3: Allowed

------------ NUKI LOCK CONFIG ACL ------------
Name: Allowed
Latitude: Allowed
Longitude: Allowed
Auto Unlatch: Allowed
Pairing enabled: Allowed
Button enabled: Allowed
LED flash enabled: Allowed
LED brightness: Allowed
Timezone offset: Allowed
DST mode: Allowed
Fob Action 1: Allowed
Fob Action 2: Allowed
Fob Action 3: Allowed
Single Lock: Allowed
Advertising Mode: Allowed
Timezone ID: Allowed
Unlocked Position Offset Degrees: Allowed
Locked Position Offset Degrees: Allowed
Single Locked Position Offset Degrees: Allowed
Unlocked To Locked Transition Offset Degrees: Allowed
Lock n Go timeout: Allowed
Single button press action: Allowed
Double button press action: Allowed
Detached cylinder: Allowed
Battery type: Allowed
Automatic battery type detection: Allowed
Unlatch duration: Allowed
Auto lock timeout: Allowed
Auto unlock disabled: Allowed
Nightmode enabled: Allowed
Nightmode start time: Allowed
Nightmode end time: Allowed
Nightmode auto lock enabled: Allowed
Nightmode auto unlock disabled: Allowed
Nightmode immediate lock on start: Allowed
Auto lock enabled: Allowed
Immediate auto lock enabled: Allowed
Auto update enabled: Allowed
Reboot Nuki: Allowed

------------ NUKI OPENER ------------
Opener enabled: No

------------ GPIO ------------
```
   
   nuki-hub2:
   
```
System Information

------------ NUKI HUB ------------
Version: 9.02
Build: 11995573722.4.1
Build type: Release
Build date: 2024-11-24
Updater version: 9.02
Updater build: 11995573722.4.1
Updater build date: 2024-11-24
Uptime (min): 909
Config version: 902
Last restart reason FW: NotApplicable
Last restart reason ESP: ESP_RST_POWERON: Reset due to power-on event.
Free internal heap: 68668
Total internal heap: 260580
PSRAM Available: No
Network task stack high watermark: 8700
Nuki task stack high watermark: 5056

------------ GENERAL SETTINGS ------------
Network task stack size: 12288
Nuki task stack size: 8192
Check for updates: No
Latest version: 
Allow update from MQTT: No
Web configurator username: Not set
Web configurator password: Not set
Web configurator enabled: Yes
Publish debug information enabled: No
MQTT log enabled: Yes
Webserial enabled: No
Bootloop protection enabled: No

------------ NETWORK ------------
Network device: Built-in Wi-Fi
Network connected: Yes
IP Address: 10.0.1.92
SSID: ms14-iot
BSSID of AP: B2:B9:8A:60:14:91
ESP32 MAC address: C8:F0:9E:4E:7B:2C

------------ NETWORK SETTINGS ------------
Nuki Hub hostname: nuki-garten
DHCP enabled: No
Static IP address: 10.0.1.92
Static IP subnet: 255.255.255.0
Static IP gateway: 10.0.1.1
Static IP DNS server: 10.0.1.1
RSSI Publish interval (s): 10000
Find WiFi AP with strongest signal: Yes
Restart ESP32 on network disconnect enabled: No
MQTT Timeout until restart (s): 600

------------ MQTT ------------
MQTT connected: Yes
MQTT broker address: 10.0.1.1
MQTT broker port: 1883
MQTT username: ***
MQTT password: ***
MQTT base topic: nuki-garten
MQTT SSL CA: Not set
MQTT SSL CRT: Not set
MQTT SSL Key: Not set

------------ BLUETOOTH ------------
Bluetooth TX power (dB): 9
Bluetooth command nr of retries: 3
Bluetooth command retry delay (ms): 200
Seconds until reboot when no BLE beacons received: -1

------------ QUERY / PUBLISH SETTINGS ------------
Lock/Opener state query interval (s): 1800
Publish Nuki device authorization log: No
Max authorization log entries to retrieve: 5
Battery state query interval (s): 1800
Most non-JSON MQTT topics disabled: Yes
Publish Nuki device config: Yes
Config query interval (s): 3600
Publish Keypad info: No
Keypad query interval (s): 1800
Enable Keypad control: Yes
Publish Keypad topic per entry: No
Publish Keypad codes: No
Allow checking Keypad codes: No
Max keypad entries to retrieve: 10
Publish timecontrol info: No
Keypad query interval (s): 1800
Enable timecontrol control: No
Publish timecontrol topic per entry: No
Max timecontrol entries to retrieve: 10

------------ HOME ASSISTANT ------------
Home Assistant auto discovery enabled: Yes
Home Assistant auto discovery topic: homeassistant/
Nuki Hub configuration URL for HA: http://10.0.1.92

------------ NUKI LOCK ------------
Lock enabled: Yes
Paired: Yes
Nuki Hub device ID: 4224542623
Nuki device ID: ***
Firmware version: 2.15.3
Hardware version: 11.2
Valid PIN set: Yes
Has door sensor: No
Has keypad: No
Timecontrol highest entries count: 0
Register as: Bridge

------------ HYBRID MODE ------------
Hybrid mode enabled: No

------------ NUKI LOCK ACL ------------
Lock: Allowed
Unlock: Allowed
Unlatch: Allowed
Lock N Go: Allowed
Lock N Go Unlatch: Allowed
Full Lock: Allowed
Fob Action 1: Allowed
Fob Action 2: Allowed
Fob Action 3: Allowed

------------ NUKI LOCK CONFIG ACL ------------
Name: Allowed
Latitude: Allowed
Longitude: Allowed
Auto Unlatch: Allowed
Pairing enabled: Allowed
Button enabled: Allowed
LED flash enabled: Allowed
LED brightness: Allowed
Timezone offset: Allowed
DST mode: Allowed
Fob Action 1: Allowed
Fob Action 2: Allowed
Fob Action 3: Allowed
Single Lock: Allowed
Advertising Mode: Allowed
Timezone ID: Allowed
Unlocked Position Offset Degrees: Allowed
Locked Position Offset Degrees: Allowed
Single Locked Position Offset Degrees: Allowed
Unlocked To Locked Transition Offset Degrees: Allowed
Lock n Go timeout: Allowed
Single button press action: Allowed
Double button press action: Allowed
Detached cylinder: Allowed
Battery type: Allowed
Automatic battery type detection: Allowed
Unlatch duration: Allowed
Auto lock timeout: Allowed
Auto unlock disabled: Allowed
Nightmode enabled: Allowed
Nightmode start time: Allowed
Nightmode end time: Allowed
Nightmode auto lock enabled: Allowed
Nightmode auto unlock disabled: Allowed
Nightmode immediate lock on start: Allowed
Auto lock enabled: Allowed
Immediate auto lock enabled: Allowed
Auto update enabled: Allowed
Reboot Nuki: Allowed

------------ NUKI OPENER ------------
Opener enabled: No

------------ GPIO ------------
```

### TO REPRODUCE

- Boot nuki_hub
- Wait one to three days until it hangs

### EXPECTED BEHAVIOUR
- no crash

### ADDITIONAL CONTEXT
- The first nuki_hub is paired with a Gen 3 Nuki lock. The second one is paired with a Gen 2 lock.
- Both are used with home assistant.
- During upgrading from 9.00 to 9.02, I had the same issues (timeout, power-cycle) described in #537 on both locks.

I'll have to downgrade one of the devices to 9.0 but I could do some tests with the other one if you have any hints how to further diagnose the problem.

**Comment by technyon** [comment] 2024-12-01 02:17
Hi,

There are a few more restart options you can configure:

- Restart ESP32 on network disconnect enabled: --> enable
- MQTT Timeout until restart: Maybe lower it, 10 minutes is quite long.
- Seconds until reboot when no BLE beacons received: Set something like 60 seconds

If this doesn't help, please let us know.

**Comment by leo-b** [comment] 2024-12-01 09:03
> There are a few more restart options you can configure:

Note that both hubs had been running stable without timeout based reboots on all versions before 9.02.

> Restart ESP32 on network disconnect enabled: --> enable

I do not want to reboot in a loop everytime an access point restarts.
The MQTT timeout restart should catch disconnects caused by network stack instability, shouldn't it?

> MQTT Timeout until restart: Maybe lower it, 10 minutes is quite long.

I did set it to to minutes on purpose: A restart or a short maintenance of the MQTT broker shouldn't cause the hub to reboot.
Besides it shouldn't make any difference if this setting is set to 10 min or to 30 seconds: It doesn't even reconnect after one day!

> Seconds until reboot when no BLE beacons received: Set something like 60 seconds

For testing I changed all three settings to the values you suggested.
But I don't expect any change, as the 10 min MQTT timeout also didn't cause a restart. When it crashes, it looses layer 2 connectivity and after 10 minutes, there doesn't seem to be a restart attempt:

```
Nov 28 16:53:08 ms14-wifi1 hostapd: wlan1-1: AP-STA-DISCONNECTED c8:f0:9e:50:1b:d0
Nov 28 16:53:08 ms14-wifi1 hostapd: wlan1-1: STA c8:f0:9e:50:1b:d0 IEEE 802.11: disassociated due to inactivity
Nov 28 16:53:09 ms14-wifi1 hostapd: wlan1-1: STA c8:f0:9e:50:1b:d0 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Nov 29 18:56:52 ms14-wifi1 hostapd: wlan1-1: STA c8:f0:9e:50:1b:d0 IEEE 802.11: authenticated
Nov 29 18:56:52 ms14-wifi1 hostapd: wlan1-1: STA c8:f0:9e:50:1b:d0 IEEE 802.11: associated (aid 1)
Nov 29 18:56:52 ms14-wifi1 hostapd: wlan1-1: AP-STA-CONNECTED c8:f0:9e:50:1b:d0
Nov 29 18:56:52 ms14-wifi1 hostapd: wlan1-1: STA c8:f0:9e:50:1b:d0 WPA: pairwise key handshake completed (RSN)
```

**Comment by technyon** [comment] 2024-12-01 12:19
It's very hard to say where the problem is without debugging your setup. I have Nuki Hub running and. It reboots every now and then, but I didn't have the issue that it becomes completely unavailable. To get some more information, I'd need serial logs. Can you keep the ESP connected to a laptop or something and record logs until it goes offline?

**Comment by kotylo** [comment] 2024-12-02 09:49
I have everything 

> Hi,
> 
> There are a few more restart options you can configure:
> 
> * Restart ESP32 on network disconnect enabled: --> enable
> * MQTT Timeout until restart: Maybe lower it, 10 minutes is quite long.
> * Seconds until reboot when no BLE beacons received: Set something like 60 seconds
> 
> If this doesn't help, please let us know.

I think we have the same issue as mine, #547. All the parameters are as you have describer by me, restart enabled, mqtt timeout 30 seconds, 60 seconds for beacons, but still it hangs.
p.s. As a workaround I have installed a smart switch and will reboot through it, once i see the status unavailable :(

**Comment by iranl** [comment] 2024-12-03 14:36
Closing as this seems to be a duplicate of #547

**Closed by iranl** 2024-12-03 14:36 UTC

**Comment by leo-b** [comment] 2024-12-03 14:43
> Closing as this seems to be a duplicate of #547

In this case the close reason should be "duplicate", not "not planned".

**Comment by iranl** [comment] 2024-12-03 15:29
Close reasons on GitHub can be completed or not planned and duplicates explicitly fall under not planned.
