### ISSUE TITLE
problem Nuki smart lock 3.0 PRO?

### ISSUE THREAD

**Issue by pilot1981** [technyon/nuki_hub#105] opened 2023-01-31 17:04 UTC
Hi,
I have problem with my MQTT config; I done it:
1) integration
2) add MQTT

itself appeared both entities related to my Nuki smart lock devices...but I'm not able to control them using MQTT commands....but if I use another MQTT client all works fine...

I notice, to use another MQTT client on my HA I addedd these lines in my configuration.yaml:

mqtt:
##SEZIONE SWITCH DI TIPO MQTT
  switch:
## lavatrice
   - name: "Lavatrice"
     command_topic: "cmnd/Lavatrice/power"
     state_topic: "stat/Lavatrice/POWER"
     availability_topic: "tele/Lavatrice/LWT"
     payload_available: "Online"
     payload_not_available: "Offline"
     payload_on: "ON"
     payload_off: "OFF"
     retain: false
##SEZIONE SENSOR DI TIPO MQTT
  sensor:
## misurazione corrente presa WIFI Lavatrice
   - name: "WATT Lavatrice"
     state_topic: "tele/Lavatrice/SENSOR"
     value_template: "{{ value_json['ENERGY'].Power }}"
     unit_of_measurement: "W"
     icon: mdi:gauge

Do you suggest to me to add also these lines in my configuration.yaml? you already know which lines I have to add?

mqtt:
##SEZIONE SWITCH DI TIPO MQTT
  switch:
## lavatrice
   - name: "Nuki1"
     command_topic: "cmnd/nuki1/lock?????"
     state_topic: "stat/nuki1????"
     availability_topic: "tele/nuki1??????"
     payload_available: "Online"
     payload_not_available: "Offline"
     payload_on: "ON"
     payload_off: "OFF"
     retain: false

let me know

regards

**Comment by technyon** [comment] 2023-01-31 17:27
Hi,

Since this is home assistant related issue, I think you're better off asking in the home assistant forum:

https://community.home-assistant.io/

**Comment by SergioWarriorPeru** [comment] 2023-01-31 19:13
> Hi, I have problem with my MQTT config; I done it:
> 
> 1. integration
> 2. add MQTT
> 
> itself appeared both entities related to my Nuki smart lock devices...but I'm not able to control them using MQTT commands....but if I use another MQTT client all works fine...
> 
> I notice, to use another MQTT client on my HA I addedd these lines in my configuration.yaml:
> 
> mqtt: ##SEZIONE SWITCH DI TIPO MQTT switch:
> 
> ## lavatrice
> * name: "Lavatrice"
>   command_topic: "cmnd/Lavatrice/power"
>   state_topic: "stat/Lavatrice/POWER"
>   availability_topic: "tele/Lavatrice/LWT"
>   payload_available: "Online"
>   payload_not_available: "Offline"
>   payload_on: "ON"
>   payload_off: "OFF"
>   retain: false
>   ##SEZIONE SENSOR DI TIPO MQTT
>   sensor:
> 
> ## misurazione corrente presa WIFI Lavatrice
> * name: "WATT Lavatrice"
>   state_topic: "tele/Lavatrice/SENSOR"
>   value_template: "{{ value_json['ENERGY'].Power }}"
>   unit_of_measurement: "W"
>   icon: mdi:gauge
> 
> Do you suggest to me to add also these lines in my configuration.yaml? you already know which lines I have to add?
> 
> mqtt: ##SEZIONE SWITCH DI TIPO MQTT switch:
> 
> ## lavatrice
> * name: "Nuki1"
>   command_topic: "cmnd/nuki1/lock?????"
>   state_topic: "stat/nuki1????"
>   availability_topic: "tele/nuki1??????"
>   payload_available: "Online"
>   payload_not_available: "Offline"
>   payload_on: "ON"
>   payload_off: "OFF"
>   retain: false
> 
> let me know
>
> regards

Hi,

I use Mosquito Broker and my Nuki appear as a device 

regards

**Comment by mundschenk-at** [comment] 2023-01-31 21:02
Hi @SergioWarriorPeru, the `mqtt` is now configured within the Home Assistant UI and Nuki Hub has auto-discovery out of the box if you set the topic in its MQTT Configuration page. I am assuming what you posted are YAML fragments, but they have got nothing to do with Nuki Hub as far as I can see. What exactly is the question you have?

**Comment by SergioWarriorPeru** [comment] 2023-01-31 21:18
> Hi @pilot1981, the `mqtt` is now configured within the Home Assistant UI and Nuki Hub has auto-discovery out of the box if you set the topic in its MQTT Configuration page. I am assuming what you posted are YAML fragments, but they have got nothing to do with Nuki Hub as far as I can see. What exactly is the question you have?
> 
> Sorry @SergioWarriorPeru, I confused you with the OP.

Not problem...I tried to say that my HA work with Mosquitom integration and Nuki hub without any problem.

**Comment by pilot1981** [comment] 2023-02-01 11:15
I confirm MQTT auto-discover worked fine and MQTT object seems look good...so I go to find my MQTT problems in other place...

**Comment by pilot1981** [comment] 2023-02-02 14:01
very strange...If I launch MQTT command from HA nothing happen...If I use an external MQTT client all works fine and then all works fine also on HA...

after some time again MQTT commands sent from HA don't works...


I don't understand...

**Comment by SergioWarriorPeru** [comment] 2023-02-02 14:12
> very strange...If I launch MQTT command from HA nothing happen...If I use an external MQTT client all works fine and then all works fine also on HA...
> 
> after some time again MQTT commands sent from HA don't works...
> 
> I don't understand...

Hi, I use Node Red in HA
![Mqtt](https://user-images.githubusercontent.com/77809496/216347777-26b2772b-41ab-41b6-9e5b-dfe595b45d73.jpg)

**Comment by pilot1981** [comment] 2023-02-05 11:11
Hi, 
I done some other tests and I found MQTT command works fine with NUKI smart lock 3.0 but it don’t works with NUKI smart lock 3.0 PRO.

I use 2 differente ESP32 with the same firmware version (the last).


Any idea?

this firmware works fine also with NUKI smart lock 3.0 PRO?

**Comment by mundschenk-at** [comment] 2023-02-05 11:48
@pilot1981 What exactly do you mean by "MQTT commands", BTW, with auto-discovery there are native HA services for almost everything (except of course the lock configuration options). To unlatch the lock, just use the `lock.open` service (whereas to just unlock it, you would use `lock.unlock`).

**Comment by technyon** [comment] 2023-02-05 11:50
The bluetooth API of the Pro lock is no different from the regular lock. It is fully supported and confirmed working with NUKI Hub.

**Comment by pilot1981** [comment] 2023-02-05 15:15
> @pilot1981 What exactly do you mean by "MQTT commands", BTW, with auto-discovery there are native HA services for almost everything (except of course the lock configuration options). To unlatch the lock, just use the `lock.open` service (whereas to just unlock it, you would use `lock.unlock`).

Lock.Unlock and lock.lock doesn’t work

**Comment by pilot1981** [comment] 2023-02-05 15:16
To troubleshoot I would know know to use MQTT logging

**Comment by mundschenk-at** [comment] 2023-02-05 15:49
> To troubleshoot I would know know to use MQTT logging

Enable MQTT logging in the preferences and have something (e.g. a HA automation) listen to the topic `<nuki>/maintenance/log`. The prefix of course depends on what you set in the Nuki Hub configuration. You did set two different prefixes for your two logs?

**Comment by pilot1981** [comment] 2023-02-06 05:16
MQTT auto-discovery don’t works for ti?

**Comment by mundschenk-at** [comment] 2023-02-06 06:36
MQTT logging is not mapped to any HA entities, thus no auto-discovery. You don't need HA for MQTT logging, it is just what I use.

**Comment by pilot1981** [comment] 2023-02-06 09:52
![image](https://user-images.githubusercontent.com/46350465/216940494-1a1cf8a0-8331-418f-8c6d-62d075503cb0.png)

**Comment by pilot1981** [comment] 2023-02-06 19:31
![F7366A69-2E46-42ED-A8D3-715230241B77](https://user-images.githubusercontent.com/46350465/217066940-16d33265-c4ab-49c5-bdc9-14109e634b68.jpeg)

**Comment by mundschenk-at** [comment] 2023-02-06 19:33
@pilot1981 Please try to re-pair after unpairing via the `Credentials` page.

**Comment by mundschenk-at** [comment] 2023-02-06 20:17
Can happen. You should increase the number of retries.

**Comment by pilot1981** [comment] 2023-02-06 20:54
I have to increase “ Number of retries if command failed”?

which value do you suggest? 10?

**Comment by technyon** [comment] 2023-02-06 20:59
Maybe go for something like 3 :)

**Comment by pilot1981** [comment] 2023-02-06 22:33
I setup 3 retries, but it don’t works

![A1612168-3E07-4119-B6BE-2BFDFF82253E](https://user-images.githubusercontent.com/46350465/217102595-74ebee96-a7e6-48ff-955c-b88f5827d055.png)

**Comment by pilot1981** [comment] 2023-02-07 09:37
I have MQTT connected, Nuki lock paired and now I have also lock state updated correctly, but I ahve always have command failed on Nuki and I found many error in reading config & reading advanced config...

There is a way to collect more data/logs?

**Comment by mundschenk-at** [comment] 2023-02-07 20:44
What's your BLE RSSI for the lock?

**Comment by pilot1981** [comment] 2023-02-08 06:21
![70615DCF-D89D-46EE-8F78-89417C2754E4](https://user-images.githubusercontent.com/46350465/217450660-efe31e5c-a7f2-4b71-89a5-e68700d359e8.png)
![3E187740-C63F-446D-BDBE-E27D15185CC4](https://user-images.githubusercontent.com/46350465/217450669-a917cb5f-5336-42a2-a9d0-0929d495716c.jpeg)

**Comment by mundschenk-at** [comment] 2023-02-08 20:56
That's pretty low for the lock. Can you try to move the ESP closer?

**Comment by pilot1981** [comment] 2023-02-09 19:26
Hi,
I moved it closer but on HA I always see -74 dbm…very strange…

There is a way to ask an updated value of BLE signal strength?

**Comment by mundschenk-at** [comment] 2023-02-09 19:32
When you view the sensor log, is it a straight line at -74 dBm? Then it's not really updating at all. `RSSI Publish interval` is not set to `-1` on the Nuki Hub?

**Comment by pilot1981** [comment] 2023-02-09 21:20
You are right: RSSI update was disabled.

after I enabled it and moved ESP32 I have -64dbm, but same error in log and no any chance to unlock/lock the door…

I can do other test? I can collect more fat/log/info?

**Comment by technyon** [comment] 2023-02-10 18:04
There must be something wrong with your ESP. Try:

- factory reset your ESP
- try different ESP

**Comment by pilot1981** [comment] 2023-02-12 11:07
Hi,
I tried to flash again original ESP32 mini v3 and it worked again for some hour, but it stop to works again…

So I flash another ESP32 mini v1 but I obtain always same error in MQTT Logs…

**Comment by technyon** [comment] 2023-02-12 11:10
Did you configure the PIN on NUKI Hub?

**Comment by pilot1981** [comment] 2023-02-12 11:47
No, I don’t configured PIN.

yesterday, when I flashed again ESP32 mini v3, I don’t configured PIN and it worked fine soon…

so, I don’t configured PIN in ESP32 mini v1

if I have problem of PIN, I should see error in MQTT logs?

**Comment by pilot1981** [comment] 2023-02-12 11:50
Now I tried to change PIN on NUKI app and update it in ESP32 nukihub, but I obtain again same error in MQTT logs…

**Comment by pilot1981** [comment] 2023-02-25 11:28
I buyed 3 newest ESP32. Tomorrow try to flash it again

**Comment by technyon** [comment] 2023-03-10 17:01
@pilot1981 Did this solve your issue?

**Comment by pilot1981** [comment] 2023-03-10 17:30
I have to wait some days to confirm...we can merge with issue #141 ?

**Comment by technyon** [comment] 2023-03-26 08:41
Closing here let's continue in issue #141

**Closed by technyon** 2023-03-26 08:41 UTC
