### ISSUE TITLE
"Enable keypad control via MQTT" Is not available

### ISSUE THREAD

**Issue by cpvbruno** [technyon/nuki_hub#103] opened 2023-01-31 10:38 UTC
I don't see "Enable keypad control via MQTT" in advanced Nuki configuration, even though I have a Keypad 2.0 connected

**Comment by knorrre** [comment] 2023-01-31 12:50
My guess is that it is a problem with the API.
https://developer.nuki.io/t/keypad-2-not-setting-has-keypad-flag-in-config-of-nuki-lock/19539

See also here:
https://github.com/technyon/nuki_hub/issues/42#issuecomment-1407374048

**Comment by cpvbruno** [comment] 2023-01-31 15:07
Indeed it seems something related to the new keypad

**Comment by technyon** [comment] 2023-01-31 15:24
I've updated the readme to make clear that at the time only Keypad 1.0 is supported. Let's hope that NUKI will provide an answer how to control Keypad 2.0.

**Comment by technyon** [comment] 2023-01-31 15:25
... also closing the issue because until keypad 2.0 is supported this is (sadly) expected behaviour.

**Closed by technyon** 2023-01-31 15:25 UTC
