### ISSUE TITLE
Future compatibility with Nuki 4.0 (not pro variant)

### ISSUE THREAD

**Issue by danielbigmac** [technyon/nuki_hub#248] opened 2023-11-16 16:03 UTC
Hi! 
As you might know, Nuki released new Matter capable locks and I just wanted to ask if I can use the new one with esp32 as well?

Kind regards,
Daniel

**Comment by mundschenk-at** [comment] 2023-11-16 17:22
Probably, but as no one has the devices yet 🤷

**Comment by technyon** [comment] 2023-11-18 03:59
NUKI Hub uses bluetooth to talk to the lock. If they keep that functionality yes. But I know as much as you do, we'll know when they release it,

**Comment by danielbigmac** [comment] 2023-11-18 08:38
Thank you!

**Comment by DEVIDTR** [comment] 2023-11-18 13:53
I have the new Lock and Bluetooth pairing fails. Or it just does no pair :-(

**Comment by noohi** [comment] 2023-11-21 11:29
> I have the new Lock and Bluetooth pairing fails. Or it just does no pair :-( I have the Pro version. Matter with Home Assistant does not work, it basically crashed my network :-(

Same here, got the 4.0 Pro with Olimex BT, does not pair. Let me know if you need some logging etc.
Thanks.

**Comment by Mikescotland** [comment] 2023-11-21 14:27
Subscribing to this issue as thorn between buying version 3.0 before they dissappear or version 4.0

**Comment by kotylo** [comment] 2023-11-21 18:17
Since it's Black Friday week, i was also torn. Opened this thread and thanks to @DEVIDTR bought the 3.0 Pro, so that i could use this component :) Would be nice to have that 6 month of battery in v4.0 though. I think it should be fixed, since new version should also support MQTT. Time will tell.

**Comment by haissio** [comment] 2023-11-22 14:05
Just for heads up:
Paired 4.0 non PRO version with this project. Everything seems to be working fine, except for the battery level that is reporting 0% everytime.
Lock is properly functional from HomeAssistant.

**Comment by noohi** [comment] 2023-11-22 18:22
> Just for heads up: Paired 4.0 non PRO version with this project. Everything seems to be working fine, except for the battery level that is reporting 0% everytime. Lock is properly functional from HomeAssistant.

Thanks, this made me try bringing the BLE Proxy closer, and indeed pairing works.
This is 4.0 Pro.
Now having the issue of MQTT Autodiscovery not working, but I'm guessing it's me somehow.

**Comment by mundschenk-at** [comment] 2023-11-22 18:27
Did you enter the topic for autodiscovery (`homeassistant` by default)?

**Comment by noohi** [comment] 2023-11-22 18:52
> Did you enter the topic for autodiscovery (`homeassistant` by default)?

Sure, will re-create MQTT integration tomorrow from scratch, Nuki's official MQTT integration is not detected either.
Thanks anyway.

**Comment by mundschenk-at** [comment] 2023-11-22 19:12
No I mean did you enter it in the NH settings? The field is empty by default and you need to explicitly enter the value you set in HA.

**Comment by noohi** [comment] 2023-11-23 11:34
> No I mean did you enter it in the NH settings? The field is empty by default and you need to explicitly enter the value you set in HA to enable autodiscovery publishing.

Yes, did that, should have been more clear.

After deleting MQTT integration, restarting MQTT Addon, and readding MQTT (v5 this time), it works.
Also I didn't know that MQTT autodiscovery adds a new device to the list without asking.
There is no standard new device detected message with an option to add it, it just does it.

Difference now is that in MQTT Explorer I do not see homeassistant lock config lingering, it's gone, so it must be working.

Thank you, will post if there are any issues.

**Comment by noohi** [comment] 2023-11-23 12:22
> But still no battery level?

Correct.
We could say the project supports new Nuki 4, only issue so far is that the battery level is stuck to 0%.
While in MQTT it has the voltage, will track that one for now, as it's very important to get notifications for battery change on time.

Now that I paired it twice, it's not about the distance, it simply needed 3-5 retries restarting the ESP32 and pushing pairing on the lock.
Tried Nuki's MQTT, then went back to this, the other one is too slow for some reason (my WLAN AP is close, so that should not be it).

**Comment by danielbigmac** [comment] 2023-11-23 12:27
So So both the 4.0 and the 4.0 Pro are supported? I'm asking because only the Pro version has been reported on

**Comment by technyon** [comment] 2023-11-23 12:42
I think it's highly likely that the 4.0 works if the 4.0 Pro does. It wouldn't make sense if they use a different bluetooth API on the regular 4.0

**Comment by noohi** [comment] 2023-11-23 14:06
> So both the 4.0 and the 4.0 Pro are supported? I'm asking because only the Pro version has been reported on
Yes, you can see above [the non-pro report](https://github.com/technyon/nuki_hub/issues/248#issuecomment-1822836795).

> If the mqtt has the battery voltage, in theory I could do a template sensor in HA that calculates the percentage from the voltage?
Sure, just need to see the range of what is the max and considered low battery.

Currently it's 5.52V, fell from 5.53V few hours ago, and it's still considered 100% in the Nuki app.

I have put the warning when it falls under 5V, then will check the Nuki app for the level adjustment.

**Comment by danielbigmac** [comment] 2023-11-23 14:09
> > So both the 4.0 and the 4.0 Pro are supported? I'm asking because only the Pro version has been reported on
> 
> Yes, you can see above [the non-pro report](https://github.com/technyon/nuki_hub/issues/248#issuecomment-1822836795).
> 
> > If the mqtt has the battery voltage, in theory I could do a template sensor in HA that calculates the percentage from the voltage?
> > Sure, just need to see the range of what is the max and considered low battery.
> 
> Currently it's 5.52V, fell from 5.53V few hours ago, and it's still considered 100% in the Nuki app.
> 
> I have put the warning when it falls under 5V, then will check the Nuki app for the level adjustment.

Oh thank you, I didn't read it properly...

**Comment by danielbigmac** [comment] 2023-11-23 18:15
Just an other question: is there any disadvantage choosing the pro version over the non-pro version? Because I think I would buy the Pro version because of MQTT Support. I am asking, because with the 3.0 Pro there was a problem that MQTT wasn´t working when the Internet Connection got lost...

**Comment by mundschenk-at** [comment] 2023-11-23 18:18
I am pretty certain it will work exactly the same way right now (and when they finally fix it, will be fixed for both HW versions).

**Comment by Mikescotland** [comment] 2023-11-23 18:19
> Since it's Black Friday week, i was also torn. Opened this thread and thanks to @DEVIDTR bought the 3.0 Pro, so that i could use this component :) Would be nice to have that 6 month of battery in v4.0 though. I think it should be fixed, since new version should also support MQTT. Time will tell.

Now I'm even more thorn, as the 3.0 is on Amazon Black Friday for £119, from £149.

Is there really a huge difference in battery life between 3.0 and 4.0?
😁

**Comment by mundschenk-at** [comment] 2023-11-23 18:33
I doubt it.

**Comment by Mikescotland** [comment] 2023-11-23 18:55
> I doubt it (if you use it with WiFi or NH).

Gonna use it over BT without the NH, using an ESP.
Can't justify £90 just for the hub...

**Comment by mundschenk-at** [comment] 2023-11-23 18:56
Sorry if that was not clear, "NH" meant NukiHub, this project, on an ESP32.

**Comment by eminga** [comment] 2023-11-23 22:43
Just updated my Nuki 4 (non pro) to FW version 4.0.31. Now it shows a battery level of 100% which is consistent with the information from the Nuki app.

**Comment by technyon** [comment] 2023-11-24 11:50
I'd say just buy the non-pro and go with NUKI Hub. An MQTT API that goes down when internet drops is rather pointless. The question about 3.0 vs. 4.0 is about future compatibility. Being able to use matter and some point in the future sounds like a nice thing to have to me, but at this point it probably won't do much for you.

**Comment by noohi** [comment] 2023-11-25 10:10
> Just updated my Nuki 4 (non pro) to FW version 4.0.31. Now it shows a battery level of 100% which is consistent with the information from the Nuki app.

Confirmed, thanks for the info.

**Comment by schmic** [comment] 2023-12-21 21:54
> I think it's highly likely that the 4.0 works if the 4.0 Pro does. It wouldn't make sense if they use a different bluetooth API on the regular 4.0

I paired my 4.0 without issues two days ago. Works like a charm, battery is reported too, can't see any issues atm.

**Comment by technyon** [comment] 2023-12-22 12:26
Thanks for confirming. I think the issue can be closed now.

**Closed** 2023-12-22 12:27 UTC

**Comment by technyon** [comment] 2023-12-27 13:12
Updated the readme to include v4
