### ISSUE TITLE
Configure MQTT presence/devices publish interval

### ISSUE THREAD

**Issue by danimaciasperea** [technyon/nuki_hub#156] opened 2023-03-26 15:27 UTC
Add an option in MQTT and Network Configuration page to configure the publish interval of the MQTT presence/devices topic.

**Comment by technyon** [comment] 2023-03-27 16:53
What's your use case that you need to configure this?

**Comment by bcutter** [comment] 2023-03-28 17:54
Maybe it's updating too frequently (impact on battery life)?

**Comment by danimaciasperea** [comment] 2023-03-28 18:01
Yes exactly, it is being updated every 3 seconds. I don't know if it is a bug (I had problems with update frequency of other topics in a previous version). Battery should not be a problem, since this is independent from the look device, right?

**Comment by bcutter** [comment] 2023-03-28 18:07
> Battery should not be a problem, since this is independent from the look device, right?

My fault. Of course, it is done by the ESP, not the SL.

That's why I'm fine and don't care about the update interval.

Having a "only update once every XX seconds" option would still be nice to limit things, but not even in my personal top ten ;-)

**Comment by technyon** [comment] 2023-03-28 18:08
Correct, there's no impact on battery life, since the lock isn't involved in presence detection at all. The ESP just publishes the adresses of whatever beacons it receives. Three seconds isn't a bug, presence detection should be up-to-date. The only concern could be that it generates network traffic, but even that is very little.

**Comment by iranl** [comment] 2024-02-29 19:06
Should this be closed as not a bug / not being worked on / won't fix?

**Comment by technyon** [comment] 2024-03-01 12:27
Yes, forgot to close it.

**Closed by technyon** 2024-03-01 12:27 UTC
