### ISSUE TITLE
[Feature] Option to disable additional lock states

### ISSUE THREAD

**Issue by Arn0uDz** [technyon/nuki_hub#477] opened 2024-09-25 13:59 UTC
### PROBLEM DESCRIPTION
I'm not sure in what version https://github.com/technyon/nuki_hub/pull/296 was released but I recently upgraded to 9.00 and I noticed that the "Unlocking" state is now shown when unlocking the Nuki. 

The state itself is okay but it has an annoying delay before it shows the next state after "Unlocking". 

This was the old sequence: Locked > *unlock command* > When it is done unlocking it gave me an immediate "Unlocked" state. I knew exactly when it was done turning. 

This is the new sequence: Locked > *unlock command* > "Unlocking" > the Nuki is physically done but the state "unlocking" remains and only after about 20 seconds updates to "Unlocked". 

The delay is killing me because I cannot determine if it is done unlocking from a remote location. I wish I could go back to only the Locked/Unlocked states without downgrading. 

Is there an option to make it a choice for the user which states to use?

Note: just to clarify, with only the Locked/Unlocked states this was instant, so it is possible without the delay.
### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [ ] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): LilyGO T-ETH-POE
- [x] Nuki Hub binary firmware version number used: 9.00
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Provide the output of http://nukihubIP/info:
```
Nuki Hub version: 9.00
Nuki Hub build: 10235422676.1.1
Nuki Hub build type: Release
run: true
confVersion: 900
deviceId: redacted
deviceIdOp: redacted
nukiId: ***
nukidOp: 
mqttbroker: 192.168.1.132
mqttport: 1883
mqttuser: ***
mqttpass: ***
mqttlog: false
checkupdates: true
websrvena: false
lockena: true
lockpin: 1
mqttpath: nuki
openerena: false
openerpin: 
openercont: false
mqttoppath: 
maxkpad: 
opmaxkpad: 
maxtc: 
opmaxtc: 
enabtlprst: false
mqttca: 
mqttcrt: 
mqttkey: 
hassdiscovery: homeassistant
hassConfigUrl: 
buffsize: 
dhcpena: true
ipaddr: 
ipsub: 
ipgtw: 
dnssrv: 
nwhw: 7
nwwififb: true
rssipb: 60
hostname: nukihub
nwbestrssi: false
nettmout: -1
restdisc: false
rstbcn: -1
lockStInterval: 1800
tcPerEntry: false
kpPerEntry: false
configInterval: 3600
batInterval: 1800
kpInterval: 1800
kpCntrlEnabled: true
kpInfoEnabled: false
kpPubCode: false
tcCntrlEnabled: false
tcInfoEnabled: false
cnfInfoEnabled: true
regAsApp: false
regOpnAsApp: false
nrRetry: 3
rtryDelay: 100
crdusr: 
crdpass: 
disnonjson: false
pubAuth: true
pubdbg: false
prdtimeout: 
offHybrid: false
hybridTimer: 600
hybridAct: false
hybridRtry: false
hasmac: false
macb0: 
macb1: 
macb2: 
latest: 
tsksznetw: 
tsksznuki: 
authmaxentry: 
kpmaxentry: 
tcmaxentry: 
updMqtt: false
showSecr: false
bleTxPwr: 
recNtwMqttDis: false
MQTT connected: Yes
Lock firmware version: 2.15.3
Lock hardware version: 11.1
Lock paired: Yes
Lock valid PIN set: Yes
Lock has door sensor: No
Lock has keypad: No
Lock ACL (Lock): Allowed
Lock ACL (Unlock): Allowed
Lock ACL (Unlatch): Allowed
Lock ACL (Lock N Go): Disallowed
Lock ACL (Lock N Go Unlatch): Disallowed
Lock ACL (Full Lock): Allowed
Lock ACL (Fob Action 1): Disallowed
Lock ACL (Fob Action 2): Disallowed
Lock ACL (Fob Action 3): Disallowed
Lock config ACL (Name): Allowed
Lock config ACL (Latitude): Allowed
Lock config ACL (Longitude): Allowed
Lock config ACL (Auto Unlatch): Allowed
Lock config ACL (Pairing enabled): Allowed
Lock config ACL (Button enabled): Allowed
Lock config ACL (LED flash enabled): Allowed
Lock config ACL (LED brightness): Allowed
Lock config ACL (Timezone offset): Allowed
Lock config ACL (DST mode): Allowed
Lock config ACL (Fob Action 1): Allowed
Lock config ACL (Fob Action 2): Allowed
Lock config ACL (Fob Action 3): Allowed
Lock config ACL (Single Lock): Allowed
Lock config ACL (Advertising Mode): Allowed
Lock config ACL (Timezone ID): Allowed
Lock config ACL (Unlocked Position Offset Degrees): Allowed
Lock config ACL (Locked Position Offset Degrees): Allowed
Lock config ACL (Single Locked Position Offset Degrees): Allowed
Lock config ACL (Unlocked To Locked Transition Offset Degrees): Allowed
Lock config ACL (Lock n Go timeout): Allowed
Lock config ACL (Single button press action): Allowed
Lock config ACL (Double button press action): Allowed
Lock config ACL (Detached cylinder): Allowed
Lock config ACL (Battery type): Allowed
Lock config ACL (Automatic battery type detection): Allowed
Lock config ACL (Unlatch duration): Allowed
Lock config ACL (Auto lock timeout): Allowed
Lock config ACL (Auto unlock disabled): Allowed
Lock config ACL (Nightmode enabled): Allowed
Lock config ACL (Nightmode start time): Allowed
Lock config ACL (Nightmode end time): Allowed
Lock config ACL (Nightmode auto lock enabled): Allowed
Lock config ACL (Nightmode auto unlock disabled): Allowed
Lock config ACL (Nightmode immediate lock on start): Allowed
Lock config ACL (Auto lock enabled): Allowed
Lock config ACL (Immediate auto lock enabled): Allowed
Lock config ACL (Auto update enabled): Allowed
Network device: LilyGO T-ETH-POE
Uptime: 8868 minutes
Heap: 90088
Stack watermarks: nw: 4580, nuki: 4944
Restart reason FW: ConfigurationUpdated
Restart reason ESP: ESP_RST_SW: Software reset via esp_restart.
```

### TO REPRODUCE
Lock and unlock the Nuki

### EXPECTED BEHAVIOUR
Only show Locked or Unlocked

### SCREENSHOTS
Here you can see that it takes 35 seconds to update it's state from "Unlocking" to "Unlocked" while the Nuki itself needs less then 10 seconds to be locked / unlocked. That means the state keeps hanging for 25 seconds on "unlocking".
![image](https://github.com/user-attachments/assets/b65a6480-da76-41ab-869c-f7662eb77298)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by technyon** [comment] 2024-09-25 14:53
A delay of 20 seconds isn't normal. for me it does show the intermediate state, but it then changes to locked or unlocked once the action is completed. Is it possible that the bluetooth reception isn't all that good? What's your bluetooth RSSI value?

**Comment by Arn0uDz** [comment] 2024-09-25 15:43
Bluetooth RSSI is around 59 / 60

But I don’t think it’s that because the Nuki unlocks and locks within a second of me giving the command from HomeAssistant. 

The binarystate changes immediately but the “hastate” always takes 35 seconds to update. Never more and never less. Like it’s on a fixed interval.

**Comment by mundschenk-at** [comment] 2024-09-25 16:25
What is your lock state refresh interval? I have noticed a bug with where `locking` sometimes gets stuck, but my lock state refresh interval is 3600 seconds.

**Comment by Arn0uDz** [comment] 2024-09-25 16:57
Lock state refresh interval is 1800. The same as it was before 9.00 when it was still updating immediately. But that was a version without “Unlocking”.

**Comment by iranl** [comment] 2024-09-25 18:02
Delay in 9.00 should not be longer than before 9.0

Your issue probably isn't related to the introduction of intermediatie states but to the "high performance" mode Nuki Hub enters after a command to pick up intermediate states. NH might run into a timeout or something when quering these intermediate states (10 sec lock/unlock is pretty  long)

You can help debugging by providing a MQTT log.

Enable MQTT logging in Nuki Hub network settings and than watch the nukihub/maintanance/log topic after publishing a lock/unlock command. Provide the complete set of messages in that MQTT topic here.

**Comment by Arn0uDz** [comment] 2024-09-25 18:27
I just timed the lock/unlocking and it's just under 5 seconds for completion. Alot shorter than I had in my mind.

I see this line "25-09-2024 20:17:27(-30.52 seconds)" if you add the 5 seconds it actually takes to lock/unlock you get the 35 seconds it takes to pass the unlocking state that I mentioned before.

MQTT log:
```
Lock:

25-09-2024 20:17:57(-55.37 seconds) 
Done querying lock state
25-09-2024 20:17:57(-0 seconds) 
locked
25-09-2024 20:17:57(-0 seconds) 
Done publishing auth data
25-09-2024 20:17:57(-0 seconds) 
Retrieve log entries: Retrieve log entries: Retrieve log entries: Retrieve log entries: error
25-09-2024 20:17:27(-30.52 seconds) 
Result (attempt 1): Publishing auth data
25-09-2024 20:17:27(-0.22 seconds) 
Querying lock state
25-09-2024 20:17:27(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:27(-0 seconds) 
Done querying lock state
25-09-2024 20:17:27(-0 seconds) 
locking
25-09-2024 20:17:27(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:26(-0.23 seconds) 
Querying lock state
25-09-2024 20:17:26(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:26(-0 seconds) 
Done querying lock state
25-09-2024 20:17:26(-0 seconds) 
locking
25-09-2024 20:17:26(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:26(-0.15 seconds) 
Querying lock state
25-09-2024 20:17:26(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:26(-0.1 seconds) 
Done querying lock state
25-09-2024 20:17:26(-0 seconds) 
locking
25-09-2024 20:17:26(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:26(-0.1 seconds) 
Querying lock state
25-09-2024 20:17:26(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:26(-0 seconds) 
Done querying lock state
25-09-2024 20:17:26(-0 seconds) 
locking
25-09-2024 20:17:26(-0.15 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:26(-0.09 seconds) 
Querying lock state
25-09-2024 20:17:26(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:26(-0.09 seconds) 
Done querying lock state
25-09-2024 20:17:26(-0 seconds) 
locking
25-09-2024 20:17:26(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:26(-0.12 seconds) 
Querying lock state
25-09-2024 20:17:26(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:26(-0 seconds) 
Done querying lock state
25-09-2024 20:17:26(-0 seconds) 
locking
25-09-2024 20:17:26(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:25(-0.23 seconds) 
Querying lock state
25-09-2024 20:17:25(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:25(-0 seconds) 
Done querying lock state
25-09-2024 20:17:25(-0 seconds) 
locking
25-09-2024 20:17:25(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:25(-0.23 seconds) 
Querying lock state
25-09-2024 20:17:25(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:25(-0 seconds) 
Done querying lock state
25-09-2024 20:17:25(-0 seconds) 
locking
25-09-2024 20:17:25(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:25(-0.2 seconds) 
Querying lock state
25-09-2024 20:17:25(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:25(-0 seconds) 
Done querying lock state
25-09-2024 20:17:25(-0 seconds) 
locking
25-09-2024 20:17:25(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:25(-0.28 seconds) 
Querying lock state
25-09-2024 20:17:25(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:25(-0 seconds) 
Done querying lock state
25-09-2024 20:17:25(-0 seconds) 
locking
25-09-2024 20:17:25(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:25(-0.2 seconds) 
Querying lock state
25-09-2024 20:17:25(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:25(-0 seconds) 
Done querying lock state
25-09-2024 20:17:25(-0 seconds) 
locking
25-09-2024 20:17:25(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:24(-0.22 seconds) 
Querying lock state
25-09-2024 20:17:24(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:24(-0 seconds) 
Done querying lock state
25-09-2024 20:17:24(-0 seconds) 
locking
25-09-2024 20:17:24(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:24(-0.11 seconds) 
Querying lock state
25-09-2024 20:17:24(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:24(-0.07 seconds) 
Done querying lock state
25-09-2024 20:17:24(-0 seconds) 
locking
25-09-2024 20:17:24(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:24(-0.14 seconds) 
Querying lock state
25-09-2024 20:17:24(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:24(-0.1 seconds) 
Done querying lock state
25-09-2024 20:17:24(-0 seconds) 
locking
25-09-2024 20:17:24(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:24(-0.1 seconds) 
Querying lock state
25-09-2024 20:17:24(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:24(-0.08 seconds) 
Done querying lock state
25-09-2024 20:17:24(-0 seconds) 
locking
25-09-2024 20:17:24(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:23(-0.1 seconds) 
Querying lock state
25-09-2024 20:17:23(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:23(-0.06 seconds) 
Done querying lock state
25-09-2024 20:17:23(-0 seconds) 
locking
25-09-2024 20:17:23(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:23(-0.13 seconds) 
Querying lock state
25-09-2024 20:17:23(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:23(-0 seconds) 
Done querying lock state
25-09-2024 20:17:23(-0 seconds) 
locking
25-09-2024 20:17:23(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:23(-0.23 seconds) 
Querying lock state
25-09-2024 20:17:23(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:23(-0 seconds) 
Done querying lock state
25-09-2024 20:17:23(-0 seconds) 
locking
25-09-2024 20:17:23(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:17:23(-0.23 seconds) 
Querying lock state
25-09-2024 20:17:23(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:17:23(-0 seconds) 
Done querying lock state


Unlock:

25-09-2024 20:20:04 
Done querying lock state
25-09-2024 20:20:04(-0 seconds) 
unlocked
25-09-2024 20:20:04(-0.05 seconds) 
Done publishing auth data
25-09-2024 20:20:04(-0 seconds) 
Retrieve log entries: Retrieve log entries: Retrieve log entries: Retrieve log entries: error
25-09-2024 20:19:33(-30.49 seconds) 
Result (attempt 1): Publishing auth data
25-09-2024 20:19:33(-0.09 seconds) 
Querying lock state
25-09-2024 20:19:33(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:33(-0.11 seconds) 
Done querying lock state
25-09-2024 20:19:33(-0 seconds) 
unlocking
25-09-2024 20:19:33(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:33(-0.14 seconds) 
Querying lock state
25-09-2024 20:19:33(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:33(-0.09 seconds) 
Done querying lock state
25-09-2024 20:19:33(-0 seconds) 
unlocking
25-09-2024 20:19:33(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:33(-0.15 seconds) 
Querying lock state
25-09-2024 20:19:33(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:33(-0.11 seconds) 
Done querying lock state
25-09-2024 20:19:33(-0 seconds) 
unlocking
25-09-2024 20:19:33(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:32(-0.1 seconds) 
Querying lock state
25-09-2024 20:19:32(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:32(-0.1 seconds) 
Done querying lock state
25-09-2024 20:19:32(-0 seconds) 
unlocking
25-09-2024 20:19:32(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:32(-0.13 seconds) 
Querying lock state
25-09-2024 20:19:32(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:32(-0 seconds) 
Done querying lock state
25-09-2024 20:19:32(-0 seconds) 
unlocking
25-09-2024 20:19:32(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:32(-0.22 seconds) 
Querying lock state
25-09-2024 20:19:32(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:32(-0 seconds) 
Done querying lock state
25-09-2024 20:19:32(-0 seconds) 
unlocking
25-09-2024 20:19:32(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:32(-0.23 seconds) 
Querying lock state
25-09-2024 20:19:32(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:32(-0 seconds) 
Done querying lock state
25-09-2024 20:19:32(-0 seconds) 
unlocking
25-09-2024 20:19:32(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:32(-0.24 seconds) 
Querying lock state
25-09-2024 20:19:32(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:32(-0 seconds) 
Done querying lock state
25-09-2024 20:19:32(-0 seconds) 
unlocking
25-09-2024 20:19:32(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:31(-0.1 seconds) 
Querying lock state
25-09-2024 20:19:31(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:31(-0.07 seconds) 
Done querying lock state
25-09-2024 20:19:31(-0 seconds) 
unlocking
25-09-2024 20:19:31(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:31(-0.1 seconds) 
Querying lock state
25-09-2024 20:19:31(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:31(-0.07 seconds) 
Done querying lock state
25-09-2024 20:19:31(-0 seconds) 
unlocking
25-09-2024 20:19:31(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:31(-0.11 seconds) 
Querying lock state
25-09-2024 20:19:31(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:31(-0.07 seconds) 
Done querying lock state
25-09-2024 20:19:31(-0 seconds) 
unlocking
25-09-2024 20:19:31(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:31(-0.11 seconds) 
Querying lock state
25-09-2024 20:19:31(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:31(-0.05 seconds) 
Done querying lock state
25-09-2024 20:19:31(-0.1 seconds) 
unlocking
25-09-2024 20:19:31(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:31(-0.1 seconds) 
Querying lock state
25-09-2024 20:19:31(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:31(-0 seconds) 
Done querying lock state
25-09-2024 20:19:31(-0 seconds) 
unlocking
25-09-2024 20:19:31(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:30(-0.22 seconds) 
Querying lock state
25-09-2024 20:19:30(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:30(-0 seconds) 
Done querying lock state
25-09-2024 20:19:30(-0 seconds) 
unlocking
25-09-2024 20:19:30(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:30(-0.23 seconds) 
Querying lock state
25-09-2024 20:19:30(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:30(-0 seconds) 
Done querying lock state
25-09-2024 20:19:30(-0 seconds) 
unlocking
25-09-2024 20:19:30(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:30(-0.21 seconds) 
Querying lock state
25-09-2024 20:19:30(-0 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:30(-0 seconds) 
Done querying lock state
25-09-2024 20:19:30(-0 seconds) 
unlocking
25-09-2024 20:19:30(-0.06 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:30(-0.11 seconds) 
Querying lock state
25-09-2024 20:19:30(-0.08 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:30(-0 seconds) 
Done querying lock state
25-09-2024 20:19:30(-0 seconds) 
unlocking
25-09-2024 20:19:30(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:30(-0.11 seconds) 
Querying lock state
25-09-2024 20:19:29(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:29(-0.07 seconds) 
Done querying lock state
25-09-2024 20:19:29(-0 seconds) 
unlocking
25-09-2024 20:19:29(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
25-09-2024 20:19:29(-0.1 seconds) 
Querying lock state
25-09-2024 20:19:29(-0.05 seconds) 
Updating Lock state based on status, timer or query
25-09-2024 20:19:29(-0.1 seconds) 
Done querying lock state
25-09-2024 20:19:29(-0 seconds) 
unlocking
25-09-2024 20:19:29(-0 seconds) 
Result (attempt 1): Lock: Keep updating status on intermediate lock state
```

**Comment by iranl** [comment] 2024-09-25 18:34
Something goes wrong while retrieving the auth log. This check times out after 30 seconds and only then is the final state published (this is by design so the auth id/name gets published along side the lock state).

Is auth logging enabled using the nuki app on your nuki lock?

If you disable publish auth in nuki hub settings you should get unlocked/locked state immediately when the lock is done unlocking/locking.

**Comment by Arn0uDz** [comment] 2024-09-25 18:46
Auth logging was enabled in the Nuki App. As I don’t use the app at all I disabled that option first. But it had no effect. 

Disabling publish auth in Nuki Hub solved my issue. 

I don’t really need publish auth but kinda weird it’s not working with it on.

**Comment by iranl** [comment] 2024-09-25 18:49
If you enable publish auth in nuki hub you should also enable it for the nuki lock using the official app.

Not sure why auth logging gives these errors in your use case while both are enabled (as it should if you need it)

But if you are satisfied with the solution as is please close the issue

**Closed** 2024-09-25 18:51 UTC

**Comment by Arn0uDz** [comment] 2024-09-25 18:52
Thanks for the help. Appreciated.
