### ISSUE TITLE
Nuki lock state: undefined

### ISSUE THREAD

**Issue by Rebislori** [technyon/nuki_hub#171] opened 2023-04-12 06:41 UTC
Ho everyone.
For the last month, the nukihub works only id i switch off the internal wifi of my smart lock 3.0 pro.

When it's switched off everything works Great and The hub is very responsive.

If i switch internal wifi on, it just stops working!
The status is always on "undefined", and no changes are registered.
Am i missing some information?

![Screenshot_2023-04-12-08-37-37-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/118441237/231372853-fe45da37-ab73-480d-9abc-762501c7c3fe.jpg)

**Comment by Rebislori** [comment] 2023-04-12 17:54
If i turn on wifi, nukihub stops working. Or better, it stays like in the picture i poste a ove.

With wifi turned off, everything works extremely well (by the way, thanks for your job!).

I just wanted to know if it's a known issue, or if i miss something in the documentation.

**Comment by technyon** [comment] 2023-04-12 19:50
You didn't miss anything, and it's not the first report wifi disables bluetooth functionality (which is I think what happens). Not all users with a Pro lock can confirm this though, I can't say for sure what's going on or what sense it makes to disable blueooth. I guess you'll have to make a choice, NUKI Hub or NUKI Cloud.

**Comment by micudaj** [comment] 2023-04-28 11:02
I have the same issue but even after disabling the wifi of the nuki 3.0 pro I still get the undefined state. Any idea what the problem might be? I paired it as an app as I have a bridge I also connected to the lock

**Comment by mundschenk-at** [comment] 2023-05-01 15:47
> I have the same issue but even after disabling the wifi of the nuki 3.0 pro I still get the undefined state. Any idea what the problem might be? I paired it as an app as I have a bridge I also connected to the lock

When paired as an app, NukiHub does not receive the necessary updates from the BLE API. This is by design (on Nuki's side).

**Comment by mundschenk-at** [comment] 2023-05-01 15:49
@technyon I think this issue can be closed as a duplicate of #141.

**Comment by technyon** [comment] 2023-05-01 18:02
Correct.

@Rebislori Due to NUKI, it's not possible to use Wifi and Bridge functionality at the same time, this is by design.

**Closed by technyon** 2023-05-01 18:02 UTC
